version: '3.9'

services:

  django:
    container_name: django
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
  
  react:
    container_name: react
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"