# Generated by Django 3.2.6 on 2021-08-30 18:21

import django.core.files.storage
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                ("file_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "file",
                    models.FileField(
                        max_length=255,
                        storage=django.core.files.storage.FileSystemStorage(),
                        upload_to="",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "txt", "jpg", "png", "mp4"]
                            )
                        ],
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
